# Generated by Django 2.0.7 on 2018-07-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180719_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogart',
            options={'verbose_name': '文章管理', 'verbose_name_plural': '文章管理'},
        ),
    ]
